name: universe
channels: !!python/tuple
- defaults
dependencies:
- conda-forge::hdf5=1.8.17=8
- conda-forge::jasper=1.900.1=3
- conda-forge::jpeg=9b=0
- conda-forge::libpng=1.6.26=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::opencv=3.1.0=np111py35_1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_1
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - protobuf==3.0.0
  - tensorflow==0.11.0
prefix: /home/vagrant/anaconda3/envs/universe
